/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BinStoresInAlabamaRouteImport } from './routes/bin-stores-in-alabama'
import { Route as IndexRouteImport } from './routes/index'

const BinStoresInAlabamaRoute = BinStoresInAlabamaRouteImport.update({
  id: '/bin-stores-in-alabama',
  path: '/bin-stores-in-alabama',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bin-stores-in-alabama': typeof BinStoresInAlabamaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bin-stores-in-alabama': typeof BinStoresInAlabamaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bin-stores-in-alabama': typeof BinStoresInAlabamaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bin-stores-in-alabama'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bin-stores-in-alabama'
  id: '__root__' | '/' | '/bin-stores-in-alabama'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinStoresInAlabamaRoute: typeof BinStoresInAlabamaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bin-stores-in-alabama': {
      id: '/bin-stores-in-alabama'
      path: '/bin-stores-in-alabama'
      fullPath: '/bin-stores-in-alabama'
      preLoaderRoute: typeof BinStoresInAlabamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinStoresInAlabamaRoute: BinStoresInAlabamaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
